version: '3.9'

services:
    database:
        container_name: oracleEnterprise_12_1
        ports: 
            - "1521:1521"
        image: "store/oracle/database-enterprise:12.2.0.1"
        env_file: 
            - database.env
        volumes:
            - E:/Data/Docker/oracleEnt12_1:/ORCL
